// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AcessoriosIsland from "./islands/AcessoriosIsland.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $BannerItem from "./islands/BannerItem.tsx";
import * as $BuyBarIsland from "./islands/BuyBarIsland.tsx";
import * as $CampanhaIsland from "./islands/CampanhaIsland.tsx";
import * as $CategoriesNewIsland from "./islands/CategoriesNewIsland.tsx";
import * as $CompareContextIsland from "./islands/CompareContextIsland.tsx";
import * as $CompareIsland from "./islands/CompareIsland.tsx";
import * as $CompreJuntoIsland from "./islands/CompreJuntoIsland.tsx";
import * as $Cookies_UsanDecoCookieIsland from "./islands/Cookies/UsanDecoCookieIsland.tsx";
import * as $DescriptionIsland from "./islands/DescriptionIsland.tsx";
import * as $DetailsIsland from "./islands/DetailsIsland.tsx";
import * as $EncontrePCGamerIdealIsland from "./islands/EncontrePCGamerIdealIsland.tsx";
import * as $GameContextIsland from "./islands/GameContextIsland.tsx";
import * as $GamesIsland from "./islands/GamesIsland.tsx";
import * as $HeaderIsland from "./islands/HeaderIsland.tsx";
import * as $InstitucionalIsland from "./islands/InstitucionalIsland.tsx";
import * as $LPs_ParaSuaEmpresaIslands_ProdSliderIsland from "./islands/LPs/ParaSuaEmpresaIslands/ProdSliderIsland.tsx";
import * as $NewsLetterIsland from "./islands/NewsLetterIsland.tsx";
import * as $OfertasFogoIsland from "./islands/OfertasFogoIsland.tsx";
import * as $PCNivelGamer from "./islands/PCNivelGamer.tsx";
import * as $PagDepartamentoIsland from "./islands/PagDepartamentoIsland.tsx";
import * as $Pop_ups_HelperButtonsIsland from "./islands/Pop-ups/HelperButtonsIsland.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $RecommendedProds from "./islands/RecommendedProds.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $SearchIsland from "./islands/SearchIsland.tsx";
import * as $SearchMenuBarIsland from "./islands/SearchMenuBarIsland.tsx";
import * as $SearchSubIsland from "./islands/SearchSubIsland.tsx";
import * as $SelectGamesIsland from "./islands/SelectGamesIsland.tsx";
import * as $ShelfIsland from "./islands/ShelfIsland.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $SpecificationIsland from "./islands/SpecificationIsland.tsx";
import * as $TesteIsland from "./islands/TesteIsland.tsx";
import * as $TesteMaylonIsland from "./islands/TesteMaylonIsland.tsx";
import * as $TrustvoxIsland from "./islands/TrustvoxIsland.tsx";
import * as $VitrineIsland from "./islands/VitrineIsland.tsx";
import * as $WishlistButton from "./islands/WishlistButton.tsx";
import * as $WishlistTesteIsland from "./islands/WishlistTesteIsland.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AcessoriosIsland.tsx": $AcessoriosIsland,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/BannerItem.tsx": $BannerItem,
    "./islands/BuyBarIsland.tsx": $BuyBarIsland,
    "./islands/CampanhaIsland.tsx": $CampanhaIsland,
    "./islands/CategoriesNewIsland.tsx": $CategoriesNewIsland,
    "./islands/CompareContextIsland.tsx": $CompareContextIsland,
    "./islands/CompareIsland.tsx": $CompareIsland,
    "./islands/CompreJuntoIsland.tsx": $CompreJuntoIsland,
    "./islands/Cookies/UsanDecoCookieIsland.tsx": $Cookies_UsanDecoCookieIsland,
    "./islands/DescriptionIsland.tsx": $DescriptionIsland,
    "./islands/DetailsIsland.tsx": $DetailsIsland,
    "./islands/EncontrePCGamerIdealIsland.tsx": $EncontrePCGamerIdealIsland,
    "./islands/GameContextIsland.tsx": $GameContextIsland,
    "./islands/GamesIsland.tsx": $GamesIsland,
    "./islands/HeaderIsland.tsx": $HeaderIsland,
    "./islands/InstitucionalIsland.tsx": $InstitucionalIsland,
    "./islands/LPs/ParaSuaEmpresaIslands/ProdSliderIsland.tsx":
      $LPs_ParaSuaEmpresaIslands_ProdSliderIsland,
    "./islands/NewsLetterIsland.tsx": $NewsLetterIsland,
    "./islands/OfertasFogoIsland.tsx": $OfertasFogoIsland,
    "./islands/PCNivelGamer.tsx": $PCNivelGamer,
    "./islands/PagDepartamentoIsland.tsx": $PagDepartamentoIsland,
    "./islands/Pop-ups/HelperButtonsIsland.tsx": $Pop_ups_HelperButtonsIsland,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/RecommendedProds.tsx": $RecommendedProds,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/SearchIsland.tsx": $SearchIsland,
    "./islands/SearchMenuBarIsland.tsx": $SearchMenuBarIsland,
    "./islands/SearchSubIsland.tsx": $SearchSubIsland,
    "./islands/SelectGamesIsland.tsx": $SelectGamesIsland,
    "./islands/ShelfIsland.tsx": $ShelfIsland,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/SpecificationIsland.tsx": $SpecificationIsland,
    "./islands/TesteIsland.tsx": $TesteIsland,
    "./islands/TesteMaylonIsland.tsx": $TesteMaylonIsland,
    "./islands/TrustvoxIsland.tsx": $TrustvoxIsland,
    "./islands/VitrineIsland.tsx": $VitrineIsland,
    "./islands/WishlistButton.tsx": $WishlistButton,
    "./islands/WishlistTesteIsland.tsx": $WishlistTesteIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
