// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/[...catchall].tsx";
import * as $$0 from "./islands/AcessoriosIsland.tsx";
import * as $$1 from "./islands/AddToCartButton.tsx";
import * as $$2 from "./islands/AddToCartButton/vtex.tsx";
import * as $$3 from "./islands/BannerItem.tsx";
import * as $$4 from "./islands/CampanhaIsland.tsx";
import * as $$5 from "./islands/CompareContextIsland.tsx";
import * as $$6 from "./islands/CompareIsland.tsx";
import * as $$7 from "./islands/CompreJuntoIsland.tsx";
import * as $$8 from "./islands/DescriptionIsland.tsx";
import * as $$9 from "./islands/DetailsIsland.tsx";
import * as $$10 from "./islands/GameContextIsland.tsx";
import * as $$11 from "./islands/GamesIsland.tsx";
import * as $$12 from "./islands/HeaderIsland.tsx";
import * as $$13 from "./islands/InstitucionalIsland.tsx";
import * as $$14 from "./islands/OfertasFogoIsland.tsx";
import * as $$15 from "./islands/PCNivelGamer.tsx";
import * as $$16 from "./islands/PagDepartamentoIsland.tsx";
import * as $$17 from "./islands/Pop-ups/HelperButtonsIsland.tsx";
import * as $$18 from "./islands/ProductImageZoom.tsx";
import * as $$19 from "./islands/RecommendedProds.tsx";
import * as $$20 from "./islands/SearchControls.tsx";
import * as $$21 from "./islands/SearchIsland.tsx";
import * as $$22 from "./islands/SearchMenuBarIsland.tsx";
import * as $$23 from "./islands/SearchSubIsland.tsx";
import * as $$24 from "./islands/SelectGamesIsland.tsx";
import * as $$25 from "./islands/ShelfIsland.tsx";
import * as $$26 from "./islands/ShippingSimulation.tsx";
import * as $$27 from "./islands/SliderJS.tsx";
import * as $$28 from "./islands/SpecificationIsland.tsx";
import * as $$29 from "./islands/TesteIsland.tsx";
import * as $$30 from "./islands/TesteMaylonIsland.tsx";
import * as $$31 from "./islands/TrustvoxIsland.tsx";
import * as $$32 from "./islands/VitrineIsland.tsx";
import * as $$33 from "./islands/WishlistButton.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/[...catchall].tsx": $1,
  },
  islands: {
    "./islands/AcessoriosIsland.tsx": $$0,
    "./islands/AddToCartButton.tsx": $$1,
    "./islands/AddToCartButton/vtex.tsx": $$2,
    "./islands/BannerItem.tsx": $$3,
    "./islands/CampanhaIsland.tsx": $$4,
    "./islands/CompareContextIsland.tsx": $$5,
    "./islands/CompareIsland.tsx": $$6,
    "./islands/CompreJuntoIsland.tsx": $$7,
    "./islands/DescriptionIsland.tsx": $$8,
    "./islands/DetailsIsland.tsx": $$9,
    "./islands/GameContextIsland.tsx": $$10,
    "./islands/GamesIsland.tsx": $$11,
    "./islands/HeaderIsland.tsx": $$12,
    "./islands/InstitucionalIsland.tsx": $$13,
    "./islands/OfertasFogoIsland.tsx": $$14,
    "./islands/PCNivelGamer.tsx": $$15,
    "./islands/PagDepartamentoIsland.tsx": $$16,
    "./islands/Pop-ups/HelperButtonsIsland.tsx": $$17,
    "./islands/ProductImageZoom.tsx": $$18,
    "./islands/RecommendedProds.tsx": $$19,
    "./islands/SearchControls.tsx": $$20,
    "./islands/SearchIsland.tsx": $$21,
    "./islands/SearchMenuBarIsland.tsx": $$22,
    "./islands/SearchSubIsland.tsx": $$23,
    "./islands/SelectGamesIsland.tsx": $$24,
    "./islands/ShelfIsland.tsx": $$25,
    "./islands/ShippingSimulation.tsx": $$26,
    "./islands/SliderJS.tsx": $$27,
    "./islands/SpecificationIsland.tsx": $$28,
    "./islands/TesteIsland.tsx": $$29,
    "./islands/TesteMaylonIsland.tsx": $$30,
    "./islands/TrustvoxIsland.tsx": $$31,
    "./islands/VitrineIsland.tsx": $$32,
    "./islands/WishlistButton.tsx": $$33,
  },
  baseUrl: import.meta.url,
};

export default manifest;
