// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/getBuyTogetherValuesBySku.ts";
import * as $$$1 from "./loaders/getFacetsByCategId.ts";
import * as $$$2 from "./loaders/getProductsSearchAPI.ts";
import * as $$$3 from "./loaders/getProductsSearchAPIProdType.ts";
import * as $$$4 from "./loaders/getSubCategories.ts";
import * as $$$5 from "./loaders/getTrustvox.ts";
import * as $$$$0 from "./routes/api/[...catchall].tsx";
import * as $$$$1 from "./routes/_app.tsx";
import * as $$$$$0 from "./islands/AcessoriosIsland.tsx";
import * as $$$$$1 from "./islands/AddToCartButton.tsx";
import * as $$$$$2 from "./islands/BannerItem.tsx";
import * as $$$$$3 from "./islands/CampanhaIsland.tsx";
import * as $$$$$4 from "./islands/CompreJuntoIsland.tsx";
import * as $$$$$5 from "./islands/DescriptionIsland.tsx";
import * as $$$$$6 from "./islands/DetailsIsland.tsx";
import * as $$$$$7 from "./islands/GameContextIsland.tsx";
import * as $$$$$8 from "./islands/GamesIsland.tsx";
import * as $$$$$9 from "./islands/HeaderIsland.tsx";
import * as $$$$$10 from "./islands/OfertasFogoIsland.tsx";
import * as $$$$$11 from "./islands/PagDepartamentoIsland.tsx";
import * as $$$$$12 from "./islands/PCNivelGamer.tsx";
import * as $$$$$13 from "./islands/ProductImageZoom.tsx";
import * as $$$$$14 from "./islands/RecommendedProds.tsx";
import * as $$$$$15 from "./islands/SearchControls.tsx";
import * as $$$$$16 from "./islands/SearchIsland.tsx";
import * as $$$$$17 from "./islands/SearchMenuBarIsland.tsx";
import * as $$$$$18 from "./islands/SearchSubIsland.tsx";
import * as $$$$$19 from "./islands/SelectGamesIsland.tsx";
import * as $$$$$20 from "./islands/ShelfIsland.tsx";
import * as $$$$$21 from "./islands/ShippingSimulation.tsx";
import * as $$$$$22 from "./islands/SliderJS.tsx";
import * as $$$$$23 from "./islands/SpecificationIsland.tsx";
import * as $$$$$24 from "./islands/TrustvoxIsland.tsx";
import * as $$$$$25 from "./islands/VitrineIsland.tsx";
import * as $$$$$26 from "./islands/WishlistButton.tsx";
import * as $$$$$$$$0 from "./sections/Acessorios.tsx";
import * as $$$$$$$$1 from "./sections/BannerGrid.tsx";
import * as $$$$$$$$2 from "./sections/BannerPLP.tsx";
import * as $$$$$$$$3 from "./sections/BannersColcha.tsx";
import * as $$$$$$$$4 from "./sections/Benefits.tsx";
import * as $$$$$$$$5 from "./sections/Campanha/Campanha.tsx";
import * as $$$$$$$$6 from "./sections/Campanha/FiltroMob.tsx";
import * as $$$$$$$$7 from "./sections/Carousel.tsx";
import * as $$$$$$$$8 from "./sections/Categories.tsx";
import * as $$$$$$$$9 from "./sections/CookieConsent.tsx";
import * as $$$$$$$$10 from "./sections/DesignSystem.tsx";
import * as $$$$$$$$11 from "./sections/EncontrePCGamerIdeal.tsx";
import * as $$$$$$$$12 from "./sections/EncontreSelectGames.tsx";
import * as $$$$$$$$13 from "./sections/Features.tsx";
import * as $$$$$$$$14 from "./sections/Footer/Footer.tsx";
import * as $$$$$$$$15 from "./sections/Footer/SignNewsletter.tsx";
import * as $$$$$$$$16 from "./sections/Highlights.tsx";
import * as $$$$$$$$17 from "./sections/LinkTree.tsx";
import * as $$$$$$$$18 from "./sections/NossosNums.tsx";
import * as $$$$$$$$19 from "./sections/OfertasFogo.tsx";
import * as $$$$$$$$20 from "./sections/PagCategEDepto/Filtro.tsx";
import * as $$$$$$$$21 from "./sections/PagCategEDepto/FiltroMob.tsx";
import * as $$$$$$$$22 from "./sections/PagCategEDepto/iconeNavegacional.tsx";
import * as $$$$$$$$23 from "./sections/PagCategEDepto/PagDepartamento.tsx";
import * as $$$$$$$$24 from "./sections/PagCategEDepto/PriceFilter.tsx";
import * as $$$$$$$$25 from "./sections/PCNivelGamer.tsx";
import * as $$$$$$$$26 from "./sections/Product/ProductCompreJunto.tsx";
import * as $$$$$$$$27 from "./sections/Product/ProductDescription.tsx";
import * as $$$$$$$$28 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$$$29 from "./sections/Product/ProductGames.tsx";
import * as $$$$$$$$30 from "./sections/Product/ProductRecommendedProds.tsx";
import * as $$$$$$$$31 from "./sections/Product/ProductSpecification.tsx";
import * as $$$$$$$$32 from "./sections/Product/ProductTrustvox.tsx";
import * as $$$$$$$$33 from "./sections/ProductShelf.tsx";
import * as $$$$$$$$34 from "./sections/ReturnH1.tsx";
import * as $$$$$$$$35 from "./sections/Search/SearchPage.tsx";
import * as $$$$$$$$36 from "./sections/SearchResult.tsx";
import * as $$$$$$$$37 from "./sections/Shelf.tsx";
import * as $$$$$$$$38 from "./sections/TitleAndText.tsx";
import * as $$$$$$$$39 from "./sections/Vitrine.tsx";
import * as $$$$$$$$40 from "./sections/WhatsApp.tsx";
import * as $$$$$$$$41 from "./sections/WishlistGallery.tsx";
import * as $live_workflows from "$live/routes/live/workflows/run.ts";
import * as $live_middleware from "$live/routes/_middleware.ts";
import * as $live_workbench from "$live/routes/live/workbench.ts";
import * as $live_invoke from "$live/routes/live/invoke/index.ts";
import * as $live_invoke_key from "$live/routes/live/invoke/[...key].ts";
import * as $live_editorData from "$live/routes/live/editorData.ts";
import * as $live_inspect from "$live/routes/live/inspect/[...block].ts";
import * as $live_release from "$live/routes/live/release.ts";
import * as $live_meta from "$live/routes/live/_meta.ts";
import * as $live_previews_block from "$live/routes/live/previews/[...block].tsx";
import * as $live_previews_index from "$live/routes/live/previews/index.tsx";
import * as $live_catchall from "$live/routes/[...catchall].tsx";
import * as i1$0 from "$live/loaders/secret.ts";
import * as i1$1 from "$live/loaders/state.ts";
import * as i1$2 from "$live/loaders/workflows/events.ts";
import * as i1$3 from "$live/loaders/workflows/get.ts";
import * as i1$$0 from "$live/handlers/devPage.ts";
import * as i1$$1 from "$live/handlers/fresh.ts";
import * as i1$$2 from "$live/handlers/proxy.ts";
import * as i1$$3 from "$live/handlers/redirect.ts";
import * as i1$$4 from "$live/handlers/router.ts";
import * as i1$$5 from "$live/handlers/routesSelection.ts";
import * as i1$$6 from "$live/handlers/workflowRunner.ts";
import * as i1$$$0 from "$live/pages/LivePage.tsx";
import * as i1$$$$0 from "$live/sections/Conditional_Beta.tsx";
import * as i1$$$$1 from "$live/sections/EmptySection.tsx";
import * as i1$$$$2 from "$live/sections/PageInclude.tsx";
import * as i1$$$$3 from "$live/sections/Slot.tsx";
import * as i1$$$$4 from "$live/sections/UseSlot.tsx";
import * as i1$$$$$0 from "$live/matchers/MatchAlways.ts";
import * as i1$$$$$1 from "$live/matchers/MatchCron.ts";
import * as i1$$$$$2 from "$live/matchers/MatchDate.ts";
import * as i1$$$$$3 from "$live/matchers/MatchDevice.ts";
import * as i1$$$$$4 from "$live/matchers/MatchEnvironment.ts";
import * as i1$$$$$5 from "$live/matchers/MatchHost.ts";
import * as i1$$$$$6 from "$live/matchers/MatchLocation.ts";
import * as i1$$$$$7 from "$live/matchers/MatchMulti.ts";
import * as i1$$$$$8 from "$live/matchers/MatchRandom.ts";
import * as i1$$$$$9 from "$live/matchers/MatchSite.ts";
import * as i1$$$$$10 from "$live/matchers/MatchUserAgent.ts";
import * as i1$$$$$$0 from "$live/flags/audience.ts";
import * as i1$$$$$$1 from "$live/flags/everyone.ts";
import * as i1$$$$$$2 from "$live/flags/flag.ts";
import * as i1$$$$$$3 from "$live/flags/multivariate.ts";
import * as i1$$$$$$$0 from "$live/actions/secrets/encrypt.ts";
import * as i1$$$$$$$1 from "$live/actions/workflows/cancel.ts";
import * as i1$$$$$$$2 from "$live/actions/workflows/signal.ts";
import * as i1$$$$$$$3 from "$live/actions/workflows/start.ts";
import * as i2$0 from "deco-sites/std/functions/butterCMSAds.ts";
import * as i2$1 from "deco-sites/std/functions/butterCMSBrands.ts";
import * as i2$2 from "deco-sites/std/functions/butterCMSCategories.ts";
import * as i2$3 from "deco-sites/std/functions/butterCMSFeaturedPosts.ts";
import * as i2$4 from "deco-sites/std/functions/butterCMSPage.ts";
import * as i2$5 from "deco-sites/std/functions/butterCMSPlaces.ts";
import * as i2$6 from "deco-sites/std/functions/butterCMSPostDetail.ts";
import * as i2$7 from "deco-sites/std/functions/butterCMSPosts.ts";
import * as i2$8 from "deco-sites/std/functions/butterCMSRelatedPosts.ts";
import * as i2$9 from "deco-sites/std/functions/occProductDetailsPage.ts";
import * as i2$10 from "deco-sites/std/functions/requestToParam.ts";
import * as i2$11 from "deco-sites/std/functions/shopifyProductDetailsPage.ts";
import * as i2$12 from "deco-sites/std/functions/shopifyProductList.ts";
import * as i2$13 from "deco-sites/std/functions/shopifyProductListingPage.ts";
import * as i2$14 from "deco-sites/std/functions/vndaProductList.ts";
import * as i2$15 from "deco-sites/std/functions/vndaProductListingPage.ts";
import * as i2$16 from "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts";
import * as i2$17 from "deco-sites/std/functions/vtexLegacyProductList.ts";
import * as i2$18 from "deco-sites/std/functions/vtexLegacyProductListingPage.ts";
import * as i2$19 from "deco-sites/std/functions/vtexLegacyRelatedProductsLoader.ts";
import * as i2$20 from "deco-sites/std/functions/vtexNavbar.ts";
import * as i2$21 from "deco-sites/std/functions/vtexProductDetailsPage.ts";
import * as i2$22 from "deco-sites/std/functions/vtexProductList.ts";
import * as i2$23 from "deco-sites/std/functions/vtexProductListingPage.ts";
import * as i2$24 from "deco-sites/std/functions/vtexSuggestions.ts";
import * as i2$25 from "deco-sites/std/functions/vtexWishlist.ts";
import * as i2$$0 from "deco-sites/std/accounts/butterCMS.ts";
import * as i2$$1 from "deco-sites/std/accounts/linxImpulse.ts";
import * as i2$$2 from "deco-sites/std/accounts/nuvemShop.ts";
import * as i2$$3 from "deco-sites/std/accounts/occ.ts";
import * as i2$$4 from "deco-sites/std/accounts/shopify.ts";
import * as i2$$5 from "deco-sites/std/accounts/vnda.ts";
import * as i2$$6 from "deco-sites/std/accounts/vtex.ts";
import * as i2$$7 from "deco-sites/std/accounts/yourViews.ts";
import * as i2$$$0 from "deco-sites/std/loaders/linxImpulse/autocompletes/popular.ts";
import * as i2$$$1 from "deco-sites/std/loaders/linxImpulse/autocompletes/suggestions.ts";
import * as i2$$$2 from "deco-sites/std/loaders/linxImpulse/pages/recommendations.ts";
import * as i2$$$3 from "deco-sites/std/loaders/linxImpulse/products/similarItems.ts";
import * as i2$$$4 from "deco-sites/std/loaders/linxImpulse/search.ts";
import * as i2$$$5 from "deco-sites/std/loaders/nuvemShop/nuvemShopProductDetailsPage.ts";
import * as i2$$$6 from "deco-sites/std/loaders/nuvemShop/nuvemShopProductList.ts";
import * as i2$$$7 from "deco-sites/std/loaders/nuvemShop/nuvemShopProductListingPage.ts";
import * as i2$$$8 from "deco-sites/std/loaders/vnda/cart.ts";
import * as i2$$$9 from "deco-sites/std/loaders/vnda/productDetailsPage.ts";
import * as i2$$$10 from "deco-sites/std/loaders/vnda/productList.ts";
import * as i2$$$11 from "deco-sites/std/loaders/vnda/productListingPage.ts";
import * as i2$$$12 from "deco-sites/std/loaders/vnda/proxy.ts";
import * as i2$$$13 from "deco-sites/std/loaders/vtex/cart.ts";
import * as i2$$$14 from "deco-sites/std/loaders/vtex/intelligentSearch/productDetailsPage.ts";
import * as i2$$$15 from "deco-sites/std/loaders/vtex/intelligentSearch/productList.ts";
import * as i2$$$16 from "deco-sites/std/loaders/vtex/intelligentSearch/productListingPage.ts";
import * as i2$$$17 from "deco-sites/std/loaders/vtex/intelligentSearch/suggestions.ts";
import * as i2$$$18 from "deco-sites/std/loaders/vtex/legacy/productDetailsPage.ts";
import * as i2$$$19 from "deco-sites/std/loaders/vtex/legacy/productList.ts";
import * as i2$$$20 from "deco-sites/std/loaders/vtex/legacy/productListingPage.ts";
import * as i2$$$21 from "deco-sites/std/loaders/vtex/legacy/relatedProductsLoader.ts";
import * as i2$$$22 from "deco-sites/std/loaders/vtex/legacy/suggestions.ts";
import * as i2$$$23 from "deco-sites/std/loaders/vtex/navbar.ts";
import * as i2$$$24 from "deco-sites/std/loaders/vtex/proxy.ts";
import * as i2$$$25 from "deco-sites/std/loaders/vtex/user.ts";
import * as i2$$$26 from "deco-sites/std/loaders/vtex/wishlist.ts";
import * as i2$$$27 from "deco-sites/std/loaders/x/font.ts";
import * as i2$$$28 from "deco-sites/std/loaders/x/image.ts";
import * as i2$$$29 from "deco-sites/std/loaders/x/redirects.ts";
import * as i2$$$30 from "deco-sites/std/loaders/x/redirectsFromCsv.ts";
import * as i2$$$$0 from "deco-sites/std/handlers/sitemap.ts";
import * as i2$$$$1 from "deco-sites/std/handlers/vtex/sitemap.ts";
import * as i2$$$$$0 from "deco-sites/std/sections/Analytics.tsx";
import * as i2$$$$$1 from "deco-sites/std/sections/configButterCMS.global.tsx";
import * as i2$$$$$2 from "deco-sites/std/sections/configLinxImpulse.global.tsx";
import * as i2$$$$$3 from "deco-sites/std/sections/configNuvemShop.tsx";
import * as i2$$$$$4 from "deco-sites/std/sections/configOCC.global.tsx";
import * as i2$$$$$5 from "deco-sites/std/sections/configShopify.global.tsx";
import * as i2$$$$$6 from "deco-sites/std/sections/configVTEX.global.tsx";
import * as i2$$$$$7 from "deco-sites/std/sections/configYourViews.global.tsx";
import * as i2$$$$$8 from "deco-sites/std/sections/SEO.tsx";
import * as i2$$$$$9 from "deco-sites/std/sections/SEOPDP.tsx";
import * as i2$$$$$10 from "deco-sites/std/sections/SEOPLP.tsx";
import * as i2$$$$$11 from "deco-sites/std/sections/VTEXPortalDataLayerCompatibility.tsx";
import * as i2$$$$$$0 from "deco-sites/std/actions/vnda/cart/addItem.ts";
import * as i2$$$$$$1 from "deco-sites/std/actions/vnda/cart/setShippingAddress.ts";
import * as i2$$$$$$2 from "deco-sites/std/actions/vnda/cart/updateCoupon.ts";
import * as i2$$$$$$3 from "deco-sites/std/actions/vnda/cart/updateItem.ts";
import * as i2$$$$$$4 from "deco-sites/std/actions/vtex/analytics/sendEvent.ts";
import * as i2$$$$$$5 from "deco-sites/std/actions/vtex/cart/addItems.ts";
import * as i2$$$$$$6 from "deco-sites/std/actions/vtex/cart/getInstallment.ts";
import * as i2$$$$$$7 from "deco-sites/std/actions/vtex/cart/removeItemAttachment.ts";
import * as i2$$$$$$8 from "deco-sites/std/actions/vtex/cart/removeItems.ts";
import * as i2$$$$$$9 from "deco-sites/std/actions/vtex/cart/simulation.ts";
import * as i2$$$$$$10 from "deco-sites/std/actions/vtex/cart/updateAttachment.ts";
import * as i2$$$$$$11 from "deco-sites/std/actions/vtex/cart/updateCoupons.ts";
import * as i2$$$$$$12 from "deco-sites/std/actions/vtex/cart/updateItemAttachment.ts";
import * as i2$$$$$$13 from "deco-sites/std/actions/vtex/cart/updateItemPrice.ts";
import * as i2$$$$$$14 from "deco-sites/std/actions/vtex/cart/updateItems.ts";
import * as i2$$$$$$15 from "deco-sites/std/actions/vtex/cart/updateProfile.ts";
import * as i2$$$$$$16 from "deco-sites/std/actions/vtex/cart/updateUser.ts";
import * as i2$$$$$$17 from "deco-sites/std/actions/vtex/newsletter/subscribe.ts";
import * as i2$$$$$$18 from "deco-sites/std/actions/vtex/notifyme.ts";
import * as i2$$$$$$19 from "deco-sites/std/actions/vtex/wishlist/addItem.ts";
import * as i2$$$$$$20 from "deco-sites/std/actions/vtex/wishlist/removeItem.ts";

const manifest = {
  "loaders": {
    "$live/loaders/secret.ts": i1$0,
    "$live/loaders/state.ts": i1$1,
    "$live/loaders/workflows/events.ts": i1$2,
    "$live/loaders/workflows/get.ts": i1$3,
    "deco-sites/shp/loaders/getBuyTogetherValuesBySku.ts": $$$0,
    "deco-sites/shp/loaders/getFacetsByCategId.ts": $$$1,
    "deco-sites/shp/loaders/getProductsSearchAPI.ts": $$$2,
    "deco-sites/shp/loaders/getProductsSearchAPIProdType.ts": $$$3,
    "deco-sites/shp/loaders/getSubCategories.ts": $$$4,
    "deco-sites/shp/loaders/getTrustvox.ts": $$$5,
    "deco-sites/std/loaders/linxImpulse/autocompletes/popular.ts": i2$$$0,
    "deco-sites/std/loaders/linxImpulse/autocompletes/suggestions.ts": i2$$$1,
    "deco-sites/std/loaders/linxImpulse/pages/recommendations.ts": i2$$$2,
    "deco-sites/std/loaders/linxImpulse/products/similarItems.ts": i2$$$3,
    "deco-sites/std/loaders/linxImpulse/search.ts": i2$$$4,
    "deco-sites/std/loaders/nuvemShop/nuvemShopProductDetailsPage.ts": i2$$$5,
    "deco-sites/std/loaders/nuvemShop/nuvemShopProductList.ts": i2$$$6,
    "deco-sites/std/loaders/nuvemShop/nuvemShopProductListingPage.ts": i2$$$7,
    "deco-sites/std/loaders/vnda/cart.ts": i2$$$8,
    "deco-sites/std/loaders/vnda/productDetailsPage.ts": i2$$$9,
    "deco-sites/std/loaders/vnda/productList.ts": i2$$$10,
    "deco-sites/std/loaders/vnda/productListingPage.ts": i2$$$11,
    "deco-sites/std/loaders/vnda/proxy.ts": i2$$$12,
    "deco-sites/std/loaders/vtex/cart.ts": i2$$$13,
    "deco-sites/std/loaders/vtex/intelligentSearch/productDetailsPage.ts":
      i2$$$14,
    "deco-sites/std/loaders/vtex/intelligentSearch/productList.ts": i2$$$15,
    "deco-sites/std/loaders/vtex/intelligentSearch/productListingPage.ts":
      i2$$$16,
    "deco-sites/std/loaders/vtex/intelligentSearch/suggestions.ts": i2$$$17,
    "deco-sites/std/loaders/vtex/legacy/productDetailsPage.ts": i2$$$18,
    "deco-sites/std/loaders/vtex/legacy/productList.ts": i2$$$19,
    "deco-sites/std/loaders/vtex/legacy/productListingPage.ts": i2$$$20,
    "deco-sites/std/loaders/vtex/legacy/relatedProductsLoader.ts": i2$$$21,
    "deco-sites/std/loaders/vtex/legacy/suggestions.ts": i2$$$22,
    "deco-sites/std/loaders/vtex/navbar.ts": i2$$$23,
    "deco-sites/std/loaders/vtex/proxy.ts": i2$$$24,
    "deco-sites/std/loaders/vtex/user.ts": i2$$$25,
    "deco-sites/std/loaders/vtex/wishlist.ts": i2$$$26,
    "deco-sites/std/loaders/x/font.ts": i2$$$27,
    "deco-sites/std/loaders/x/image.ts": i2$$$28,
    "deco-sites/std/loaders/x/redirects.ts": i2$$$29,
    "deco-sites/std/loaders/x/redirectsFromCsv.ts": i2$$$30,
  },
  "routes": {
    "./routes/_app.tsx": $$$$1,
    "./routes/_middleware.ts": $live_middleware,
    "./routes/[...catchall].tsx": $live_catchall,
    "./routes/api/[...catchall].tsx": $$$$0,
    "./routes/index.tsx": $live_catchall,
    "./routes/live/_meta.ts": $live_meta,
    "./routes/live/editorData.ts": $live_editorData,
    "./routes/live/inspect/[...block].ts": $live_inspect,
    "./routes/live/invoke/[...key].ts": $live_invoke_key,
    "./routes/live/invoke/index.ts": $live_invoke,
    "./routes/live/previews/[...block].tsx": $live_previews_block,
    "./routes/live/previews/index.tsx": $live_previews_index,
    "./routes/live/release.ts": $live_release,
    "./routes/live/workbench.ts": $live_workbench,
    "./routes/live/workflows/run.ts": $live_workflows,
  },
  "islands": {
    "./islands/AcessoriosIsland.tsx": $$$$$0,
    "./islands/AddToCartButton.tsx": $$$$$1,
    "./islands/BannerItem.tsx": $$$$$2,
    "./islands/CampanhaIsland.tsx": $$$$$3,
    "./islands/CompreJuntoIsland.tsx": $$$$$4,
    "./islands/DescriptionIsland.tsx": $$$$$5,
    "./islands/DetailsIsland.tsx": $$$$$6,
    "./islands/GameContextIsland.tsx": $$$$$7,
    "./islands/GamesIsland.tsx": $$$$$8,
    "./islands/HeaderIsland.tsx": $$$$$9,
    "./islands/OfertasFogoIsland.tsx": $$$$$10,
    "./islands/PagDepartamentoIsland.tsx": $$$$$11,
    "./islands/PCNivelGamer.tsx": $$$$$12,
    "./islands/ProductImageZoom.tsx": $$$$$13,
    "./islands/RecommendedProds.tsx": $$$$$14,
    "./islands/SearchControls.tsx": $$$$$15,
    "./islands/SearchIsland.tsx": $$$$$16,
    "./islands/SearchMenuBarIsland.tsx": $$$$$17,
    "./islands/SearchSubIsland.tsx": $$$$$18,
    "./islands/SelectGamesIsland.tsx": $$$$$19,
    "./islands/ShelfIsland.tsx": $$$$$20,
    "./islands/ShippingSimulation.tsx": $$$$$21,
    "./islands/SliderJS.tsx": $$$$$22,
    "./islands/SpecificationIsland.tsx": $$$$$23,
    "./islands/TrustvoxIsland.tsx": $$$$$24,
    "./islands/VitrineIsland.tsx": $$$$$25,
    "./islands/WishlistButton.tsx": $$$$$26,
  },
  "sections": {
    "$live/sections/Conditional_Beta.tsx": i1$$$$0,
    "$live/sections/EmptySection.tsx": i1$$$$1,
    "$live/sections/PageInclude.tsx": i1$$$$2,
    "$live/sections/Slot.tsx": i1$$$$3,
    "$live/sections/UseSlot.tsx": i1$$$$4,
    "deco-sites/shp/sections/Acessorios.tsx": $$$$$$$$0,
    "deco-sites/shp/sections/BannerGrid.tsx": $$$$$$$$1,
    "deco-sites/shp/sections/BannerPLP.tsx": $$$$$$$$2,
    "deco-sites/shp/sections/BannersColcha.tsx": $$$$$$$$3,
    "deco-sites/shp/sections/Benefits.tsx": $$$$$$$$4,
    "deco-sites/shp/sections/Campanha/Campanha.tsx": $$$$$$$$5,
    "deco-sites/shp/sections/Campanha/FiltroMob.tsx": $$$$$$$$6,
    "deco-sites/shp/sections/Carousel.tsx": $$$$$$$$7,
    "deco-sites/shp/sections/Categories.tsx": $$$$$$$$8,
    "deco-sites/shp/sections/CookieConsent.tsx": $$$$$$$$9,
    "deco-sites/shp/sections/DesignSystem.tsx": $$$$$$$$10,
    "deco-sites/shp/sections/EncontrePCGamerIdeal.tsx": $$$$$$$$11,
    "deco-sites/shp/sections/EncontreSelectGames.tsx": $$$$$$$$12,
    "deco-sites/shp/sections/Features.tsx": $$$$$$$$13,
    "deco-sites/shp/sections/Footer/Footer.tsx": $$$$$$$$14,
    "deco-sites/shp/sections/Footer/SignNewsletter.tsx": $$$$$$$$15,
    "deco-sites/shp/sections/Highlights.tsx": $$$$$$$$16,
    "deco-sites/shp/sections/LinkTree.tsx": $$$$$$$$17,
    "deco-sites/shp/sections/NossosNums.tsx": $$$$$$$$18,
    "deco-sites/shp/sections/OfertasFogo.tsx": $$$$$$$$19,
    "deco-sites/shp/sections/PagCategEDepto/Filtro.tsx": $$$$$$$$20,
    "deco-sites/shp/sections/PagCategEDepto/FiltroMob.tsx": $$$$$$$$21,
    "deco-sites/shp/sections/PagCategEDepto/iconeNavegacional.tsx": $$$$$$$$22,
    "deco-sites/shp/sections/PagCategEDepto/PagDepartamento.tsx": $$$$$$$$23,
    "deco-sites/shp/sections/PagCategEDepto/PriceFilter.tsx": $$$$$$$$24,
    "deco-sites/shp/sections/PCNivelGamer.tsx": $$$$$$$$25,
    "deco-sites/shp/sections/Product/ProductCompreJunto.tsx": $$$$$$$$26,
    "deco-sites/shp/sections/Product/ProductDescription.tsx": $$$$$$$$27,
    "deco-sites/shp/sections/Product/ProductDetails.tsx": $$$$$$$$28,
    "deco-sites/shp/sections/Product/ProductGames.tsx": $$$$$$$$29,
    "deco-sites/shp/sections/Product/ProductRecommendedProds.tsx": $$$$$$$$30,
    "deco-sites/shp/sections/Product/ProductSpecification.tsx": $$$$$$$$31,
    "deco-sites/shp/sections/Product/ProductTrustvox.tsx": $$$$$$$$32,
    "deco-sites/shp/sections/ProductShelf.tsx": $$$$$$$$33,
    "deco-sites/shp/sections/ReturnH1.tsx": $$$$$$$$34,
    "deco-sites/shp/sections/Search/SearchPage.tsx": $$$$$$$$35,
    "deco-sites/shp/sections/SearchResult.tsx": $$$$$$$$36,
    "deco-sites/shp/sections/Shelf.tsx": $$$$$$$$37,
    "deco-sites/shp/sections/TitleAndText.tsx": $$$$$$$$38,
    "deco-sites/shp/sections/Vitrine.tsx": $$$$$$$$39,
    "deco-sites/shp/sections/WhatsApp.tsx": $$$$$$$$40,
    "deco-sites/shp/sections/WishlistGallery.tsx": $$$$$$$$41,
    "deco-sites/std/sections/Analytics.tsx": i2$$$$$0,
    "deco-sites/std/sections/configButterCMS.global.tsx": i2$$$$$1,
    "deco-sites/std/sections/configLinxImpulse.global.tsx": i2$$$$$2,
    "deco-sites/std/sections/configNuvemShop.tsx": i2$$$$$3,
    "deco-sites/std/sections/configOCC.global.tsx": i2$$$$$4,
    "deco-sites/std/sections/configShopify.global.tsx": i2$$$$$5,
    "deco-sites/std/sections/configVTEX.global.tsx": i2$$$$$6,
    "deco-sites/std/sections/configYourViews.global.tsx": i2$$$$$7,
    "deco-sites/std/sections/SEO.tsx": i2$$$$$8,
    "deco-sites/std/sections/SEOPDP.tsx": i2$$$$$9,
    "deco-sites/std/sections/SEOPLP.tsx": i2$$$$$10,
    "deco-sites/std/sections/VTEXPortalDataLayerCompatibility.tsx": i2$$$$$11,
  },
  "name": "deco-sites/shp",
  "handlers": {
    "$live/handlers/devPage.ts": i1$$0,
    "$live/handlers/fresh.ts": i1$$1,
    "$live/handlers/proxy.ts": i1$$2,
    "$live/handlers/redirect.ts": i1$$3,
    "$live/handlers/router.ts": i1$$4,
    "$live/handlers/routesSelection.ts": i1$$5,
    "$live/handlers/workflowRunner.ts": i1$$6,
    "deco-sites/std/handlers/sitemap.ts": i2$$$$0,
    "deco-sites/std/handlers/vtex/sitemap.ts": i2$$$$1,
  },
  "pages": {
    "$live/pages/LivePage.tsx": i1$$$0,
  },
  "matchers": {
    "$live/matchers/MatchAlways.ts": i1$$$$$0,
    "$live/matchers/MatchCron.ts": i1$$$$$1,
    "$live/matchers/MatchDate.ts": i1$$$$$2,
    "$live/matchers/MatchDevice.ts": i1$$$$$3,
    "$live/matchers/MatchEnvironment.ts": i1$$$$$4,
    "$live/matchers/MatchHost.ts": i1$$$$$5,
    "$live/matchers/MatchLocation.ts": i1$$$$$6,
    "$live/matchers/MatchMulti.ts": i1$$$$$7,
    "$live/matchers/MatchRandom.ts": i1$$$$$8,
    "$live/matchers/MatchSite.ts": i1$$$$$9,
    "$live/matchers/MatchUserAgent.ts": i1$$$$$10,
  },
  "flags": {
    "$live/flags/audience.ts": i1$$$$$$0,
    "$live/flags/everyone.ts": i1$$$$$$1,
    "$live/flags/flag.ts": i1$$$$$$2,
    "$live/flags/multivariate.ts": i1$$$$$$3,
  },
  "actions": {
    "$live/actions/secrets/encrypt.ts": i1$$$$$$$0,
    "$live/actions/workflows/cancel.ts": i1$$$$$$$1,
    "$live/actions/workflows/signal.ts": i1$$$$$$$2,
    "$live/actions/workflows/start.ts": i1$$$$$$$3,
    "deco-sites/std/actions/vnda/cart/addItem.ts": i2$$$$$$0,
    "deco-sites/std/actions/vnda/cart/setShippingAddress.ts": i2$$$$$$1,
    "deco-sites/std/actions/vnda/cart/updateCoupon.ts": i2$$$$$$2,
    "deco-sites/std/actions/vnda/cart/updateItem.ts": i2$$$$$$3,
    "deco-sites/std/actions/vtex/analytics/sendEvent.ts": i2$$$$$$4,
    "deco-sites/std/actions/vtex/cart/addItems.ts": i2$$$$$$5,
    "deco-sites/std/actions/vtex/cart/getInstallment.ts": i2$$$$$$6,
    "deco-sites/std/actions/vtex/cart/removeItemAttachment.ts": i2$$$$$$7,
    "deco-sites/std/actions/vtex/cart/removeItems.ts": i2$$$$$$8,
    "deco-sites/std/actions/vtex/cart/simulation.ts": i2$$$$$$9,
    "deco-sites/std/actions/vtex/cart/updateAttachment.ts": i2$$$$$$10,
    "deco-sites/std/actions/vtex/cart/updateCoupons.ts": i2$$$$$$11,
    "deco-sites/std/actions/vtex/cart/updateItemAttachment.ts": i2$$$$$$12,
    "deco-sites/std/actions/vtex/cart/updateItemPrice.ts": i2$$$$$$13,
    "deco-sites/std/actions/vtex/cart/updateItems.ts": i2$$$$$$14,
    "deco-sites/std/actions/vtex/cart/updateProfile.ts": i2$$$$$$15,
    "deco-sites/std/actions/vtex/cart/updateUser.ts": i2$$$$$$16,
    "deco-sites/std/actions/vtex/newsletter/subscribe.ts": i2$$$$$$17,
    "deco-sites/std/actions/vtex/notifyme.ts": i2$$$$$$18,
    "deco-sites/std/actions/vtex/wishlist/addItem.ts": i2$$$$$$19,
    "deco-sites/std/actions/vtex/wishlist/removeItem.ts": i2$$$$$$20,
  },
  "functions": {
    "deco-sites/std/functions/butterCMSAds.ts": i2$0,
    "deco-sites/std/functions/butterCMSBrands.ts": i2$1,
    "deco-sites/std/functions/butterCMSCategories.ts": i2$2,
    "deco-sites/std/functions/butterCMSFeaturedPosts.ts": i2$3,
    "deco-sites/std/functions/butterCMSPage.ts": i2$4,
    "deco-sites/std/functions/butterCMSPlaces.ts": i2$5,
    "deco-sites/std/functions/butterCMSPostDetail.ts": i2$6,
    "deco-sites/std/functions/butterCMSPosts.ts": i2$7,
    "deco-sites/std/functions/butterCMSRelatedPosts.ts": i2$8,
    "deco-sites/std/functions/occProductDetailsPage.ts": i2$9,
    "deco-sites/std/functions/requestToParam.ts": i2$10,
    "deco-sites/std/functions/shopifyProductDetailsPage.ts": i2$11,
    "deco-sites/std/functions/shopifyProductList.ts": i2$12,
    "deco-sites/std/functions/shopifyProductListingPage.ts": i2$13,
    "deco-sites/std/functions/vndaProductList.ts": i2$14,
    "deco-sites/std/functions/vndaProductListingPage.ts": i2$15,
    "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts": i2$16,
    "deco-sites/std/functions/vtexLegacyProductList.ts": i2$17,
    "deco-sites/std/functions/vtexLegacyProductListingPage.ts": i2$18,
    "deco-sites/std/functions/vtexLegacyRelatedProductsLoader.ts": i2$19,
    "deco-sites/std/functions/vtexNavbar.ts": i2$20,
    "deco-sites/std/functions/vtexProductDetailsPage.ts": i2$21,
    "deco-sites/std/functions/vtexProductList.ts": i2$22,
    "deco-sites/std/functions/vtexProductListingPage.ts": i2$23,
    "deco-sites/std/functions/vtexSuggestions.ts": i2$24,
    "deco-sites/std/functions/vtexWishlist.ts": i2$25,
  },
  "accounts": {
    "deco-sites/std/accounts/butterCMS.ts": i2$$0,
    "deco-sites/std/accounts/linxImpulse.ts": i2$$1,
    "deco-sites/std/accounts/nuvemShop.ts": i2$$2,
    "deco-sites/std/accounts/occ.ts": i2$$3,
    "deco-sites/std/accounts/shopify.ts": i2$$4,
    "deco-sites/std/accounts/vnda.ts": i2$$5,
    "deco-sites/std/accounts/vtex.ts": i2$$6,
    "deco-sites/std/accounts/yourViews.ts": i2$$7,
  },
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
