// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/getBuyTogetherValuesBySku.ts";
import * as $$$1 from "./loaders/getFacetsByCategId.ts";
import * as $$$2 from "./loaders/getFacetsQueryString.ts";
import * as $$$3 from "./loaders/getParamFps.ts";
import * as $$$4 from "./loaders/getProductsSearchAPI.ts";
import * as $$$5 from "./loaders/getProductsSearchAPIProdType.ts";
import * as $$$6 from "./loaders/getSubCategories.ts";
import * as $$$7 from "./loaders/getTrustvox.ts";
import * as $$$$$$0 from "./sections/Acessorios.tsx";
import * as $$$$$$1 from "./sections/BannerGrid.tsx";
import * as $$$$$$2 from "./sections/BannerPLP.tsx";
import * as $$$$$$3 from "./sections/BannersColcha.tsx";
import * as $$$$$$4 from "./sections/Benefits.tsx";
import * as $$$$$$5 from "./sections/Campanha/Campanha.tsx";
import * as $$$$$$6 from "./sections/Campanha/FiltroMob.tsx";
import * as $$$$$$7 from "./sections/Carousel.tsx";
import * as $$$$$$8 from "./sections/Categories.tsx";
import * as $$$$$$9 from "./sections/Compare/Compare.tsx";
import * as $$$$$$10 from "./sections/Compare/CompareModal.tsx";
import * as $$$$$$11 from "./sections/CookieConsent.tsx";
import * as $$$$$$12 from "./sections/DesignSystem.tsx";
import * as $$$$$$13 from "./sections/Despacho24h.tsx";
import * as $$$$$$14 from "./sections/EncontrePCGamerIdeal.tsx";
import * as $$$$$$15 from "./sections/EncontreSelectGames.tsx";
import * as $$$$$$16 from "./sections/Features.tsx";
import * as $$$$$$17 from "./sections/Footer/Footer.tsx";
import * as $$$$$$18 from "./sections/Footer/SignNewsletter.tsx";
import * as $$$$$$19 from "./sections/Header/Header.tsx";
import * as $$$$$$20 from "./sections/Highlights.tsx";
import * as $$$$$$21 from "./sections/Institucional/Institucional.tsx";
import * as $$$$$$22 from "./sections/Institucional/InstitucionalContato.tsx";
import * as $$$$$$23 from "./sections/LinkTree.tsx";
import * as $$$$$$24 from "./sections/NossosNums.tsx";
import * as $$$$$$25 from "./sections/OfertasFogo.tsx";
import * as $$$$$$26 from "./sections/PagCategEDepto/Filtro.tsx";
import * as $$$$$$27 from "./sections/PagCategEDepto/FiltroMob.tsx";
import * as $$$$$$28 from "./sections/PagCategEDepto/iconeNavegacional.tsx";
import * as $$$$$$29 from "./sections/PagCategEDepto/PagDepartamento.tsx";
import * as $$$$$$30 from "./sections/PagCategEDepto/PriceFilter.tsx";
import * as $$$$$$31 from "./sections/PCNivelGamer.tsx";
import * as $$$$$$32 from "./sections/Pop-ups/HelperButtons.tsx";
import * as $$$$$$33 from "./sections/Product/ProductBuyBar.tsx";
import * as $$$$$$34 from "./sections/Product/ProductCompreJunto.tsx";
import * as $$$$$$35 from "./sections/Product/ProductDescription.tsx";
import * as $$$$$$36 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$37 from "./sections/Product/ProductGames.tsx";
import * as $$$$$$38 from "./sections/Product/ProductRecommendedProds.tsx";
import * as $$$$$$39 from "./sections/Product/ProductSpecification.tsx";
import * as $$$$$$40 from "./sections/Product/ProductTrustvox.tsx";
import * as $$$$$$41 from "./sections/ProductShelf.tsx";
import * as $$$$$$42 from "./sections/ReturnH1.tsx";
import * as $$$$$$43 from "./sections/Search/SearchPage.tsx";
import * as $$$$$$44 from "./sections/SearchResult.tsx";
import * as $$$$$$45 from "./sections/Shelf.tsx";
import * as $$$$$$46 from "./sections/TesteProMaylon.tsx";
import * as $$$$$$47 from "./sections/TesteSection.tsx";
import * as $$$$$$48 from "./sections/TitleAndText.tsx";
import * as $$$$$$49 from "./sections/Vitrine.tsx";
import * as $$$$$$50 from "./sections/WhatsApp.tsx";
import * as $$$$$$51 from "./sections/WishlistGallery.tsx";
import * as $$$$$$52 from "./sections/WishlistTeste.tsx";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "loaders": {
    "deco-sites/shp/loaders/getBuyTogetherValuesBySku.ts": $$$0,
    "deco-sites/shp/loaders/getFacetsByCategId.ts": $$$1,
    "deco-sites/shp/loaders/getFacetsQueryString.ts": $$$2,
    "deco-sites/shp/loaders/getParamFps.ts": $$$3,
    "deco-sites/shp/loaders/getProductsSearchAPI.ts": $$$4,
    "deco-sites/shp/loaders/getProductsSearchAPIProdType.ts": $$$5,
    "deco-sites/shp/loaders/getSubCategories.ts": $$$6,
    "deco-sites/shp/loaders/getTrustvox.ts": $$$7,
  },
  "sections": {
    "deco-sites/shp/sections/Acessorios.tsx": $$$$$$0,
    "deco-sites/shp/sections/BannerGrid.tsx": $$$$$$1,
    "deco-sites/shp/sections/BannerPLP.tsx": $$$$$$2,
    "deco-sites/shp/sections/BannersColcha.tsx": $$$$$$3,
    "deco-sites/shp/sections/Benefits.tsx": $$$$$$4,
    "deco-sites/shp/sections/Campanha/Campanha.tsx": $$$$$$5,
    "deco-sites/shp/sections/Campanha/FiltroMob.tsx": $$$$$$6,
    "deco-sites/shp/sections/Carousel.tsx": $$$$$$7,
    "deco-sites/shp/sections/Categories.tsx": $$$$$$8,
    "deco-sites/shp/sections/Compare/Compare.tsx": $$$$$$9,
    "deco-sites/shp/sections/Compare/CompareModal.tsx": $$$$$$10,
    "deco-sites/shp/sections/CookieConsent.tsx": $$$$$$11,
    "deco-sites/shp/sections/DesignSystem.tsx": $$$$$$12,
    "deco-sites/shp/sections/Despacho24h.tsx": $$$$$$13,
    "deco-sites/shp/sections/EncontrePCGamerIdeal.tsx": $$$$$$14,
    "deco-sites/shp/sections/EncontreSelectGames.tsx": $$$$$$15,
    "deco-sites/shp/sections/Features.tsx": $$$$$$16,
    "deco-sites/shp/sections/Footer/Footer.tsx": $$$$$$17,
    "deco-sites/shp/sections/Footer/SignNewsletter.tsx": $$$$$$18,
    "deco-sites/shp/sections/Header/Header.tsx": $$$$$$19,
    "deco-sites/shp/sections/Highlights.tsx": $$$$$$20,
    "deco-sites/shp/sections/Institucional/Institucional.tsx": $$$$$$21,
    "deco-sites/shp/sections/Institucional/InstitucionalContato.tsx": $$$$$$22,
    "deco-sites/shp/sections/LinkTree.tsx": $$$$$$23,
    "deco-sites/shp/sections/NossosNums.tsx": $$$$$$24,
    "deco-sites/shp/sections/OfertasFogo.tsx": $$$$$$25,
    "deco-sites/shp/sections/PagCategEDepto/Filtro.tsx": $$$$$$26,
    "deco-sites/shp/sections/PagCategEDepto/FiltroMob.tsx": $$$$$$27,
    "deco-sites/shp/sections/PagCategEDepto/iconeNavegacional.tsx": $$$$$$28,
    "deco-sites/shp/sections/PagCategEDepto/PagDepartamento.tsx": $$$$$$29,
    "deco-sites/shp/sections/PagCategEDepto/PriceFilter.tsx": $$$$$$30,
    "deco-sites/shp/sections/PCNivelGamer.tsx": $$$$$$31,
    "deco-sites/shp/sections/Pop-ups/HelperButtons.tsx": $$$$$$32,
    "deco-sites/shp/sections/Product/ProductBuyBar.tsx": $$$$$$33,
    "deco-sites/shp/sections/Product/ProductCompreJunto.tsx": $$$$$$34,
    "deco-sites/shp/sections/Product/ProductDescription.tsx": $$$$$$35,
    "deco-sites/shp/sections/Product/ProductDetails.tsx": $$$$$$36,
    "deco-sites/shp/sections/Product/ProductGames.tsx": $$$$$$37,
    "deco-sites/shp/sections/Product/ProductRecommendedProds.tsx": $$$$$$38,
    "deco-sites/shp/sections/Product/ProductSpecification.tsx": $$$$$$39,
    "deco-sites/shp/sections/Product/ProductTrustvox.tsx": $$$$$$40,
    "deco-sites/shp/sections/ProductShelf.tsx": $$$$$$41,
    "deco-sites/shp/sections/ReturnH1.tsx": $$$$$$42,
    "deco-sites/shp/sections/Search/SearchPage.tsx": $$$$$$43,
    "deco-sites/shp/sections/SearchResult.tsx": $$$$$$44,
    "deco-sites/shp/sections/Shelf.tsx": $$$$$$45,
    "deco-sites/shp/sections/TesteProMaylon.tsx": $$$$$$46,
    "deco-sites/shp/sections/TesteSection.tsx": $$$$$$47,
    "deco-sites/shp/sections/TitleAndText.tsx": $$$$$$48,
    "deco-sites/shp/sections/Vitrine.tsx": $$$$$$49,
    "deco-sites/shp/sections/WhatsApp.tsx": $$$$$$50,
    "deco-sites/shp/sections/WishlistGallery.tsx": $$$$$$51,
    "deco-sites/shp/sections/WishlistTeste.tsx": $$$$$$52,
  },
  "apps": {
    "deco-sites/shp/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/shp/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/shp",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
